namespace RenderNorth.DisplaySwitcher.UI;
internal sealed class RnEmptyState : RnCard
{
    public RnEmptyState(Action capture, Action create)
    {
        Dock = DockStyle.Top; AutoSize = true; AutoSizeMode = AutoSizeMode.GrowAndShrink; BorderColor = Color.FromArgb(64, RnTheme.Accent); Padding = new Padding(LayoutTokens.HeroInset); var root = new TableLayoutPanel { Dock = DockStyle.Fill, AutoSize = true, ColumnCount = 1, RowCount = 5, BackColor = Color.Transparent };
        var mark = new RnStarMark { Anchor = AnchorStyles.None, Size = new Size(52,52) }; root.Controls.Add(mark,0,0); root.Controls.Add(new Label { Text = "Welcome to RenderNorth Environments", ForeColor = RnTheme.PrimaryText, Font = new Font("Segoe UI Semibold", 18), AutoSize = true, Anchor = AnchorStyles.None },0,1); root.Controls.Add(new Label { Text = "Your PC should adapt to what you're doing.\nCreate your first environment by saving your current display setup.", ForeColor = RnTheme.SecondaryText, AutoSize = true, TextAlign = ContentAlignment.MiddleCenter, Anchor = AnchorStyles.None },0,2);
        var tiles = new FlowLayoutPanel { Dock = DockStyle.Fill, AutoSize = true, AutoScroll = false, WrapContents = true, FlowDirection = FlowDirection.LeftToRight, Anchor = AnchorStyles.None, Padding = new Padding(4) }; foreach(var item in new[]{("◇", "Gaming", RnTheme.Purple),("⌘", "Development", Color.FromArgb(58,161,255)),("◉", "Streaming", Color.FromArgb(255,69,83)),("▣", "Presentation", RnTheme.Success),("✈", "Travel", RnTheme.Accent)}) { var tile = new RnButton(RnTheme.Control) { Text = item.Item1 + "  " + item.Item2, AccentColor = item.Item3, Size = new Size(132, LayoutTokens.ButtonHeight), Margin = new Padding(4) }; tile.Click += (_,_) => capture(); tiles.Controls.Add(tile); } root.Controls.Add(tiles,0,3);
        var actions = new FlowLayoutPanel { Dock = DockStyle.Fill, AutoSize = true, AutoSizeMode = AutoSizeMode.GrowAndShrink, FlowDirection = FlowDirection.LeftToRight, WrapContents = true, Anchor = AnchorStyles.None }; var cap = new RnButton(Color.FromArgb(38,198,190)) { Text = "Capture Current Setup", AutoSize = true, MinimumSize = new Size(180, LayoutTokens.ButtonHeight) }; cap.Click += (_,_) => capture(); var newEnv = new RnButton(Color.FromArgb(53,64,70)) { Text = "New Environment", AutoSize = true, MinimumSize = new Size(150, LayoutTokens.ButtonHeight) }; newEnv.Click += (_,_) => create(); actions.Controls.AddRange([cap,newEnv]); root.Controls.Add(actions,0,4); Controls.Add(root);
    }
}
